__author__ = 'bakeneko'
from pygame import Color



#Activity 3

SIZE_MULTIPLIER=2.5

#Activity 05


BLACK = Color('black')
FPS = 60
SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 640, 480

ORIGINAL_BLOCK_SIZE = 16
SIZE_MULTIPLIER = 2
BLOCK_SIZE = ORIGINAL_BLOCK_SIZE * SIZE_MULTIPLIER
GROUND_HEIGHT = SCREEN_HEIGHT - BLOCK_SIZE * 2

#Activity 07

FIEND_WALK, \
FIEND_FALLING, \
FIEND_JUMPED_ON = range(0,3)
LEFT = -1
RIGHT = 1

BACKGROUND_BLUE = (113, 144, 254)


SCENARIO_BIG_HILL = 1
SCENARIO_SMALL_HILL = 2