__author__ = 'bakeneko'
from pygame import Color



#Activity 3

SIZE_MULTIPLIER=2.5

#Activity 05

BLACK = Color('black')
FPS = 60
SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 640, 480

ORIGINAL_BLOCK_SIZE = 16
SIZE_MULTIPLIER = 2
BLOCK_SIZE = ORIGINAL_BLOCK_SIZE * SIZE_MULTIPLIER
GROUND_HEIGHT = SCREEN_HEIGHT - BLOCK_SIZE * 2